[package]
authors = ["Ignas Rumbavicius <rumbavicius@gmail.com>"]
name = "zeno"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "zeno"
path = "src/main.rs"

[dependencies]
zeno-core = { path = "../core" }
