[package]
authors = ["Ignas Rumbavicius <rumbavicius@gmail.com>"]
name = "importer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "zeno-import"
path = "src/main.rs"

[dependencies]
zeno-core = { path = "../core" }
getopts = "0.2.21"

