[package]
authors = ["Ignas Rumbavicius <rumbavicius@gmail.com>"]
name = "emulator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "zeno-emulator"
path = "src/main.rs"

[dependencies]
zeno-core = { path = "../core" }
sdl2 = "0.36.0"
